<?php
/**
 * BaseController.php
 * Created by PhpStorm.
 * User: chenli
 * Time: 2018-10-18 17:50
 */

namespace App\Http\Controllers\Admin;


use App\Http\Controllers\Controller;

class BaseController extends Controller
{
    public function callAction($method, $parameters)
    {
        $userInfo = session('adminInfo');
        //var_dump($userInfo);die;
        if(!$userInfo){
            return redirect('admin/login.html');
        }
        return parent::callAction($method, $parameters); // TODO: Change the autogenerated stub
    }
}