<?php
/**
 * AuthController.php
 * Created by PhpStorm.
 * User: chenli
 * Time: 2018-10-12 14:10
 */

namespace App\Http\Controllers;


class AuthController extends BaseController
{
    public function callAction($method, $parameters)
    {
        $userInfo = session('userInfo');
        if(!$userInfo){
            return redirect('login.html');
        }
     
        if($userInfo['verify'] == 0){
            echo '邮箱未验证。';die;
        }
        return parent::callAction($method, $parameters); // TODO: Change the autogenerated stub
    }
}