<?php
/**
 * BaseController.php
 * Created by PhpStorm.
 * User: chenli
 * Time: 2018-10-04 18:47
 */

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class BaseController extends Controller
{
    // 书的基础目录
    protected $rootPath = '/wwwroot/gitbook';

    protected $userInfo = null;

    public function __construct()
    {
        // 保存当前的uri
        session(['userUri'=>url()->full()]);
    }

    public function callAction($method, $parameters)
    {

        $userInfo = session('userInfo');
        //var_dump($userInfo);die;
        if(!$userInfo){
            return redirect('login.html');
        }

        $this->userInfo = $userInfo;
        //var_dump($this->userInfo['username']);die;
        /*$this->userInfo = [
            'id' => 1,
            'username' => 'chenli'
        ];*/

        return parent::callAction($method, $parameters); // TODO: Change the autogenerated stub
    }



}